version: "3.8"

services:
  db:
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    image: postgres:16.1-bookworm
volumes:
  postgres-data:
